0.9.4.12 - fixed a bug which caused GETs to fail with     *hcpsdk.HcpsdkError: faulty read: 'NoneType' object has no attribute 'read'*     caused by idletimer cutting off the connection while transferring data